"""MTGA Collection & Deck Scanner — macOS Memory-Scanning via pymem-osx."""

from .deck_scanner import (
    DeckMemoryResult,
    DeckScanResult,
    PILE_COMMAND_ZONE,
    PILE_COMPANIONS,
    PILE_MAIN,
    PILE_SIDEBOARD,
    find_deck_blocks,
    merge_deck_results,
    parse_deck_block,
    parse_pile_list_from_bytes,
    parse_piles_from_bytes,
    scan_decks,
    write_deck_artifacts,
)

from .il2cpp_nav import (
    DeckNavResult,
    IL2CPP_OFFSETS,
    Il2CppDeckResult,
    Il2CppReader,
    Il2CppScanResult,
    MockMemory,
    MemoryReader,
    PymemMemoryAdapter,
    discover_data_segment_base,
    find_class_by_name,
    find_papa_instance,
    get_class_fields,
    navigate_to_all_decks,
    read_deck,
    read_dictionary_uint_ptr,
    read_il2cpp_string,
    read_list_of_structs,
    scan_decks_il2cpp,
)

from .rank_scanner import (
    AccountInfo,
    FullRankScanResult,
    RankInfo,
    RankScanResult,
    RANK_CLASS_NAMES,
    format_account_summary,
    format_account_table,
    format_rank_summary,
    format_rank_table,
    rank_class_name,
    scan_account_from_instance,
    scan_ranks,
    scan_ranks_and_account,
    scan_ranks_from_instance,
)

__all__ = [
    # Pattern-based deck scanner
    "DeckMemoryResult",
    "DeckScanResult",
    "PILE_COMMAND_ZONE",
    "PILE_COMPANIONS",
    "PILE_MAIN",
    "PILE_SIDEBOARD",
    "find_deck_blocks",
    "merge_deck_results",
    "parse_deck_block",
    "parse_pile_list_from_bytes",
    "parse_piles_from_bytes",
    "scan_decks",
    "write_deck_artifacts",
    # IL2CPP navigation scanner
    "DeckNavResult",
    "IL2CPP_OFFSETS",
    "Il2CppDeckResult",
    "Il2CppReader",
    "Il2CppScanResult",
    "MockMemory",
    "MemoryReader",
    "PymemMemoryAdapter",
    "discover_data_segment_base",
    "find_class_by_name",
    "find_papa_instance",
    "get_class_fields",
    "navigate_to_all_decks",
    "read_deck",
    "read_dictionary_uint_ptr",
    "read_il2cpp_string",
    "read_list_of_structs",
    "scan_decks_il2cpp",
    # Rank & account scanner
    "AccountInfo",
    "FullRankScanResult",
    "RankInfo",
    "RankScanResult",
    "RANK_CLASS_NAMES",
    "format_account_summary",
    "format_account_table",
    "format_rank_summary",
    "format_rank_table",
    "rank_class_name",
    "scan_account_from_instance",
    "scan_ranks",
    "scan_ranks_and_account",
    "scan_ranks_from_instance",
]
